"""v_3

Revision ID: 028c2e7d5819
Revises: 4038bab62ea7
Create Date: 2021-09-28 19:57:42.001847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028c2e7d5819'
down_revision = '4038bab62ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tasks', 'is_completed')
    # ### end Alembic commands ###
