"""Second

Revision ID: 26f947d1f9a2
Revises: ab04cee0be68
Create Date: 2021-09-28 18:53:06.134644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f947d1f9a2'
down_revision = 'ab04cee0be68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tasks_id'), 'users_tasks', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tasks_id'), table_name='users_tasks')
    op.drop_table('users_tasks')
    # ### end Alembic commands ###
